# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ha-client
    binary: ha-client
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: rnorth
    name: ha-client
  draft: false
  prerelease: auto

brews:
  - name: ha-client
    homepage: "https://github.com/rnorth/ha-client"
    description: "kubectl-style CLI for Home Assistant"
    license: "MIT"
    directory: Formula
    repository:
      owner: rnorth
      name: homebrew-ha-client
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update formula for {{ .ProjectName }} {{ .Tag }}"
    install: |
      bin.install "ha-client"

changelog:
  disable: true
