# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ha-client
    binary: ha-client
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: rnorth
    name: ha-client
  draft: false
  prerelease: auto

changelog:
  disable: true
